#!/bin/bash

export MAIN_DIR="$HOME/github/insta-rice/sketchybar"
export MAIN_ITEM_DIR="$MAIN_DIR/items"
export MAIN_PLUGIN_DIR="$MAIN_DIR/plugins"

source "$MAIN_DIR/colours.sh"

winXP_bar --bar	position=bottom \
        	height=40 \
                blur_radius=30 \
        	color=0xff335ad2 \
		hidden=on

default=(
  icon.font="SF Pro:Semibold:15.0"
  icon.color=$ICON_COLOUR
  label.font="SF Pro:Semibold:15.0"
  label.color=$LABEL_COLOUR
  background.color=$BG_COLOUR
  background.corner_radius=7
  background.height=24
  background.padding_left=2
  background.padding_right=2
  label.padding_left=8
  label.padding_right=10
  icon.padding_left=15
  icon.padding_right=4
)
winXP_bar --default "${default[@]}"

if [[ $wallpaper == "windows xp.jpg" ]]; then
	winXP_bar --bar hidden=off
fi

#Left side items
winXP_bar	--add item start left \
		--set start \
		background.image='/Users/alexstuart/Desktop/icons/images/winXP/XP Button.png' \
		click_script='osascript -e '\''tell application "System Events" to keystroke space using {command down}'\''' \
		background.color=$CLEAR

winXP_bar 	--add	item explorer left \
		--set	explorer \
		background.image=/Users/alexstuart/Desktop/icons/images/winXP/internet_explorer_22592.png \
		click_script='open -a "Brave Browser"' \
		background.image.scale=0.07 \
		background.color=$CLEAR \
		background.padding_right=0 \
		label.padding_right=0

winXP_bar	--add item front_app left \
		--set front_app \
		script="$MAIN_PLUGIN_DIR/front_app.sh" \
		icon.font="sketchybar-app-font:Regular:16.0" \
		background.color=0xff4c7feb \
		label.color=$WHITE \
		icon.color=$WHITE \
		width=220 \
		padding_left=0 \
		background.height=33 \
		--subscribe front_app front_app_switched

winXP_bar	--add item time right \
            	--set time \
		script="$MAIN_PLUGIN_DIR/winXP/time.sh" \
		update_freq=10 \
		background.color=0xff408ae2 \
		click_script='open "https://calendar.proton.me/u/7/month"' \
		label.color=$WHITE \
		icon.color=0xff3c59cb \
		width=dynamic \
		background.height=40 \
		background.corner_radius=0 \
		padding_right=0 \
		padding_left=0 \
		icon.padding_left=5 \
		icon.padding_right=0
				
source "$ITEM_DIR/winXP/time.sh"
winXP_bar --set time		
background.color=0xff408ae2 \
				

	

##### Force all scripts to run the first time (never do this in a script) #####
winXP_bar --update

