#!/bin/bash

export MAIN_DIR="~/github/insta-rice/sketchybar"
export MAIN_ITEM_DIR="$MAIN_DIR/items"
export MAIN_PLUGIN_DIR="$MAIN_DIR/plugins"

source "$MAIN_DIR/colours.sh"

sketchybar --bar  position=top \
                  height=40 \
                  blur_radius=30 \
                  color=$BAR_COLOUR \
		  hidden=on

default=(
  background.color=$BG_COLOUR
  background.corner_radius=7
  background.height=24
  background.padding_left=2
  background.padding_right=2
  label.color=$LABEL_COLOUR
  label.font="SF Pro:Semibold:15.0"
  label.padding_left=4
  label.padding_right=10
  icon.color=$ICON_COLOUR
  icon.font="SF Pro:Semibold:15.0"
  icon.padding_left=10
  icon.padding_right=4
)
sketchybar --default "${default[@]}"




if [[ $wallpaper == "windows xp.jpg" ]]; then
	winXP_bar --reload
	sketchybar --bar hidden=on
else
	winXP_bar --bar 
