#!/bin/bash

CONFIG_DIR="$HOME/github/insta-rice/sketchybar"

source "$CONFIG_DIR/colours.sh" #Loads all defined colours

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bottom_bar --bar  position=bottom \
                  height=40 \
                  blur_radius=30 \
                  color=0xff335ad2

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  icon.font="SF Pro:Semibold:15.0"
  icon.color=$ICON_COLOUR
  label.font="SF Pro:Semibold:15.0"
  label.color=$LABEL_COLOUR
  background.color=$BG_COLOUR
  background.corner_radius=7
  background.height=24
  padding_left=0
  padding_right=2
  label.padding_left=4
  label.padding_right=10
  icon.padding_left=10
  icon.padding_right=4
)
bottom_bar --default "${default[@]}"


#Left side items
source $ITEM_DIR/winXP/start.sh

##### Force all scripts to run the first time (never do this in a script) #####
bottom_bar --update

