#!/bin/zsh

export MAIN_DIR="$HOME/github/insta-rice/sketchybar"
export MAIN_PLUGIN_DIR="$MAIN_DIR/plugins"
source "$MAIN_DIR/colours.sh"

bottom_bar --bar  position=bottom \
                  height=40 \
                  blur_radius=30 \
                  color=$BAR_COLOUR \
#		  hidden=on

default=(
  background.color=$BG_COLOUR
  background.corner_radius=7
  background.height=24
  background.padding_left=2
  background.padding_right=2
  label.color=$LABEL_COLOUR
  label.font="SF Pro:Semibold:15.0"
  label.padding_left=4
  label.padding_right=10
  icon.color=$ICON_COLOUR
  icon.font="SF Pro:Semibold:15.0"
  icon.padding_left=10
  icon.padding_right=4
)
bottom_bar --default "${default[@]}"

if [[ $wallpaper == "windows xp.jpg" ]]; then
	bottom_bar --bar hidden=on
fi

#LEFT
bottom_bar 	--add item volume left \
		--set volume script="$MAIN_PLUGIN_DIR/volume.sh" \
		--subscribe volume volume_change

#CENTRE
bottom_bar	--add item quotes center \
		--set quotes \
		script="$MAIN_PLUGIN_DIR/quotes.sh" \
		icon="􀉚" \
		scroll_texts=on \
		label.max_chars=160 \
		label.scroll_duration=1200 \
		background.color=$BG_COLOUR_ALT \
		label.color=$LABEL_COLOUR_ALT \
		icon.color=$ICON_COLOUR_ALT

#RIGHT
bottom_bar	--add item image right \
		--set image \
		background.image='/Users/alexstuart/Library/CloudStorage/ProtonDrive-alexdnstuart@protonmail.com-folder/03-reactions/picture/live slug reaction/548e333442bb6c0ca7adb565f4018fd5.jpg' \
		background.image.scale=0.065 \
		background.color=$CLEAR
#~~~~~~~~~~~~~~~~~~
bottom_bar --update

